use_frameworks!

target 'PodTest_Example' do
  pod 'PodTest', :path => '../'

  target 'PodTest_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
